# -*- coding: utf-8 -*-
"""cell-segmentation-viewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loShqq8FvEVdBqSMD9ZivmOWBi4wT5T9
"""

import numpy as np
import gradio as gr
import tensorflow as tf
import matplotlib.pyplot as plt

from skimage.measure import regionprops
from skimage.segmentation import watershed
from skimage.morphology import erosion, dilation, disk
from scipy import ndimage as ndi

from huggingface_hub import hf_hub_download


# ---------------------------------------------------------
# Load model + test data
# ---------------------------------------------------------

MODEL_PATH = hf_hub_download(
    repo_id="JSku-Systems/unet-bccd-model",
    filename="best_model.keras"
)

X_TEST_PATH = hf_hub_download(
    repo_id="JSku-Systems/bccd-test-data",
    filename="X_test.npy"
)

Y_TEST_PATH = hf_hub_download(
    repo_id="JSku-Systems/bccd-test-data",
    filename="y_test.npy"
)


model = tf.keras.models.load_model(MODEL_PATH, compile=False)

X_test = np.load(X_TEST_PATH)   # (N, 256, 256, 3)
y_test = np.load(Y_TEST_PATH)   # (N, 256, 256, 1)

IMG_SIZE = 256
THRESHOLD = 0.90  # calibrated threshold


# ---------------------------------------------------------
# Utility functions
# ---------------------------------------------------------
def to_rgb(img):
    """Ensure image is RGB uint8."""
    if img.ndim == 2:
        img = np.stack([img] * 3, axis=-1)
    if img.ndim == 3 and img.shape[-1] == 1:
        img = np.repeat(img, 3, axis=-1)
    if img.ndim == 3 and img.shape[-1] == 4:
        img = img[:, :, :3]

    # Convert to uint8 safely
    if img.dtype != np.uint8:
        img = np.clip(img, 0, 1)
        img = (img * 255).astype(np.uint8)

    return img


def color_map_instances(labeled_mask):
    """Colour each instance with a distinct colour."""
    if labeled_mask.max() == 0:
        return np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)

    cmap = plt.get_cmap("nipy_spectral")
    norm = labeled_mask.astype(np.float32) / (labeled_mask.max() + 1)
    colored = cmap(norm)[..., :3]
    colored = (colored * 255).astype(np.uint8)

    return to_rgb(colored)


def calculate_metrics(gt, pred_bin):
    """Compute IoU and Dice."""
    gt = gt.astype(bool)
    pred_bin = pred_bin.astype(bool)

    inter = np.logical_and(gt, pred_bin).sum()
    union = np.logical_or(gt, pred_bin).sum()
    iou = inter / union if union > 0 else 0.0

    denom = gt.sum() + pred_bin.sum()
    dice = (2 * inter) / denom if denom > 0 else 0.0

    return iou, dice


def overlay_mask(image, mask, color=(1.0, 0.0, 0.0), alpha=0.4):
    """Overlay binary mask on RGB image."""
    img = image.astype(np.float32)
    if img.max() > 1:
        img = img / 255.0

    m = (mask > 0.5).astype(np.float32)

    overlay = img.copy()
    for c in range(3):
        overlay[..., c] = np.where(
            m > 0,
            (1 - alpha) * img[..., c] + alpha * color[c],
            img[..., c]
        )

    return to_rgb(overlay)


# ---------------------------------------------------------
# Watershed instance segmentation
# ---------------------------------------------------------
def marker_controlled_watershed(binary_mask):
    distance = ndi.distance_transform_edt(binary_mask)

    selem = disk(2)
    sure_fg = erosion(binary_mask, selem)
    sure_bg = dilation(~binary_mask.astype(bool), selem)

    markers, _ = ndi.label(sure_fg)
    labeled_ws = watershed(-distance, markers, mask=binary_mask)

    return labeled_ws


# ---------------------------------------------------------
# Main inference function
# ---------------------------------------------------------
def analyse_image(index, show_overlay):
    index = int(index)

    # Load data
    image = X_test[index]
    gt_mask = y_test[index][..., 0]

    # Predict
    pred = model.predict(np.expand_dims(image, axis=0))[0][..., 0]
    pred_bin = (pred > THRESHOLD).astype(np.uint8)

    # Instances
    labeled = marker_controlled_watershed(pred_bin)
    cell_count = len(regionprops(labeled))

    # Prepare displays
    raw_rgb = to_rgb(image)
    gt_display = to_rgb(gt_mask * 255)
    bin_display = to_rgb(pred_bin * 255)
    instance_colored = color_map_instances(labeled)

    # Raw or overlay
    if show_overlay:
        raw_or_overlay = overlay_mask(raw_rgb, pred_bin)
    else:
        raw_or_overlay = raw_rgb

    # Metrics (Markdown)
    iou, dice = calculate_metrics(gt_mask, pred_bin)
    metrics_text = (
        f"**IoU:** {iou:.3f} | "
        f"**Dice:** {dice:.3f} | "
        f"**Cell count:** {cell_count}"
    )

    return (
        raw_or_overlay,
        instance_colored,
        gt_display,
        bin_display,
        metrics_text,
    )


# ---------------------------------------------------------
# Gradio UI
# ---------------------------------------------------------
with gr.Blocks(title="Cell Segmentation Viewer") as demo:
    gr.Markdown("# Cell Segmentation Viewer")

    with gr.Row():
        index_input = gr.Slider(
            0, len(X_test) - 1, step=1,
            label="Test Image Index", value=0
        )
        overlay_toggle = gr.Checkbox(
            label="Show overlay on raw image", value=False
        )

    # 2×2 grid
    with gr.Row():
        raw_img = gr.Image(label="Raw Image / Overlay")
        instance_img = gr.Image(label="Instance Map")

    with gr.Row():
        gt_img = gr.Image(label="Ground Truth Mask")
        bin_pred_img = gr.Image(label="Predicted Mask (Binary)")

    # Metrics below
    metrics_box = gr.Markdown()

    # Bind events
    index_input.change(
        fn=analyse_image,
        inputs=[index_input, overlay_toggle],
        outputs=[raw_img, instance_img, gt_img, bin_pred_img, metrics_box],
    )

    overlay_toggle.change(
        fn=analyse_image,
        inputs=[index_input, overlay_toggle],
        outputs=[raw_img, instance_img, gt_img, bin_pred_img, metrics_box],
    )

demo.launch()